library(data.table)
library(bigsnpr)

# What ancestry are we currently extracting the genotype data for? - need to run script once per ancestry (or modify to loop accordingly)
ancestry <- "EUR"

# Genetic correlation is computed for each chromosome separately
for (this_chr in 1:22) { 
  # Load filtered SNP data for this chromosome generated by the previous script
  geno <- snp_attach(sprintf("data/ldpred2/%s/filtered_chr%s.rds", ancestry, this_chr)) 

  # Get genetic distance from 1000G
  gendist <- snp_asGeneticPos(
    infos.chr = geno$map$chromosome, 
    infos.pos = geno$map$physical.pos,
    dir = "data/1000G/genetic_maps/interpolated_OMNI/"
  )

  # Compute LD
  gencorr <- snp_cor(
    Gna = geno$genotypes, 
    infos.pos = gendist, 
    size = 3 / 1000,
    ncores = 10 # How many cores to parallise the LD calculations?
  ) 

  # Save out
  saveRDS(gencorr, file=sprintf("data/ldpred2/%s/filtered_chr%s_ldcorr.rds", ancestry, this_chr))
}

