#!/bin/bash

# Submit as a job the script 'src/ukb_validation/compute_all_T2D_PRS.sh' 
# Note, this requires that script to have been uploaded to the UKB RAP already
dx run swiss-army-knife \
  -iin="src/ukb_validation/compute_all_T2D_PRS.sh" \
  -icmd="sh src/ukb_validation/compute_all_T2D_PRS.sh" \
  -imount_inputs=true \
  --destination=PRS_levels \
  --instance-type="mem3_ssd1_v2_x8" \
  --tag="pgsc_calc" \
  --priority="normal" \
  --brief --yes
  